FROM node:14-alpine

# RUN apt update

# RUN apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

RUN npm install -g pm2
# RUN npm install -g yarn
RUN npm install --quiet -g node-gyp

WORKDIR /quiwi_web
